# SITE CONFIGURATION
title: Luhao's blog # your site title
author: luhao-yang # You :P
description: > # Meta description of Homepage
  This is Luhao's personal blog website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://luhao-yang.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Luhao Yang
  links:
    - https://twitter.com/yangluhao123
    - https://www.linkedin.com/in/luhaoyang
    - https://github.com/luhao-yang


# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Category', link: '/categories'}
  - {name: 'Tag', link: '/tags'}
  - {name: 'About', link: '/about'}

tagline: >
  "The palest ink is better than the best memory"

hero_img: uploads/sleek_lg.jpg # Main background image:

email: yangluhao123@gmail.com # email for form submission

twitter_username: yangluhao123 # replace with your_twitter_username or comment to remove link from footer
github_username:  luhao-yang # replace with your_github_username or comment to remove link from footer
instagram_username: luhao.yang # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: luhao # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: false

include: ['_pages']
# permalink: /:title

# https://cloudcannon.com/community/jekyll-cheat-sheet/
# https://jekyllrb.com/docs/pagination/
# https://github.com/jekyll/jekyll-paginate/issues/40
paginate: 20
#paginate_path: "/posts/page:num/"

# tags and categories are not supported

# https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md
# pagination:
#   enabled: true
#   per_page: 3
#   offset: 2
#   permalink: '/page/:num/'
#   title: ':title - page :num of :max'
#   limit: 0
#   sort_field: 'date'
#   sort_reverse: true


# https://talk.jekyllrb.com/t/paginate-v2-with-github-pages-confusion/6471/21




# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null

# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - gulpfile.js


compress_html:
  clippings: all

plugins:
  - github-pages
  # - jekyll-paginate-v2
